# Copyright 2018 SuperDARN
#
# logging_config.yaml 
# 2018-11-05
# Configuration for pydarn's logging.

# author: 
# Marina Schmidt 

#Logging in python sources: 
#https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/
#https://docs.python.org/3/howto/logging.html

# version number needs to be 1, cannot start at 0 
version: 1
# formatter for the logger to use when logging the information. 
formatters:
    # This print the following format: 2018-11-05 15:39:49,678 pydarn: 
    pydarn_fmt:
        format: '%(asctime)s %(name)s: %(message)s'
    pydarn_error_fmt:
        format: '%(asctime)s %(name)s: ERROR %(message)s'
# handlers are used a way to set levels, formats, and classes for the logger.
handlers:
    # used for testing purposes. 
    console: 
        class: logging.StreamHandler # logger class that streams log messages
        level: DEBUG
        formatter: pydarn_fmt
        stream: ext://sys.stdout 
    # should always be used in the code 
    debug_file_handler:
        class: logging.handlers.RotatingFileHandler # logs information to a file
        level: DEBUG
        formatter: pydarn_fmt
        maxBytes: 10485760 
        backupCount: 20
        encoding: utf8
    # use with exceptions and other potential errors
    error_file_handler:
        class: logging.handlers.RotatingFileHandler 
        level: ERROR
        formatter: pydarn_error_fmt
        maxBytes: 10485760 
        backupCount: 20
        encoding: utf8
loggers:
    # defualt logger code should use.
    # Specific for the pydarn library 
    pydarn:
        level: INFO
        handlers: [debug_file_handler, error_file_handler]
        propagate: no
    # logger of choice for testing. 
    pydarn_error:
        level: DEBUG
        handlers: [console, debug_file_handler, error_file_handler]
        propagate: no
    # needs to be specified, requirement of the logging library. 
    # DO NOT USE! Libraries should not use the root as this will 
    # ruin the users logger (if they use one)
    root:
        level: INFO
        handlers: [console]
